from themes.colors import *

themes = {
    "Default": {
        "start_color": ORANGE,
        "end_color": TURQUOISE,
        "path_color": PURPLE,
        "barrier_color": BLACK,
        "open_color": GREEN,
        "plane_color": WHITE,
        "closed_color": RED,
        "bg_color": GREY,
    },
    "Night": {
        "start_color": TURQUOISE,
        "end_color": YELLOW,
        "path_color": WHITE,
        "barrier_color": BLACK,
        "open_color": GREEN,
        "plane_color": WHITE,
        "closed_color": RED,
        "bg_color": BLACK,
    },
    "Synth": {
        "start_color": BLUE,
        "end_color": RED,
        "path_color": YELLOW,
        "barrier_color": BLACK,
        "open_color": GREEN,
        "plane_color": WHITE,
        "closed_color": RED,
        "bg_color": BLACK,
    },
    "Ocean": {
        "start_color": BLUE,
        "end_color": CYAN,
        "path_color": LIGHT_BLUE,
        "barrier_color": DARK_BLUE,
        "open_color": AQUA,
        "plane_color": WHITE,
        "closed_color": RED,
        "bg_color": LIGHT_BLUE,
    },
    "Forest": {
        "start_color": GREEN,
        "end_color": YELLOW,
        "path_color": LIGHT_GREEN,
        "barrier_color": DARK_GREEN,
        "open_color": LIME,
        "plane_color": WHITE,
        "closed_color": RED,
        "bg_color": LIGHT_GREEN,
    },
}
