from themes.colors import *

themes = {
    "Default": {
        "start_color": MAGENTA,
        "end_color": RED,
        "barrier_color": BLACK,
        "weight_color": BROWN,
        "look_color": BRIGHT_CYAN,
        "open_color_1": BRIGHT_GREEN,
        "open_color_2": DARK_GREEN,
        "closed_color_1": CYAN,
        "closed_color_2": DARK_CYAN,
        "closed_color_3": TEAL,
        "path_color_1": GOLD,
        "path_color_2": PALE_YELLOW,
        "path_color_3": LIME_GREEN,
        "plane_color": WHITE,
        "bg_color": LIGHT_GREY,
        "grid_color": LIGHT_GREY,
    },
    "Night": {
        "start_color": MAGENTA,
        "end_color": RED,
        "barrier_color": BLACK,
        "weight_color": BROWN,
        "look_color": BRIGHT_CYAN,
        "open_color_1": BRIGHT_GREEN,
        "open_color_2": DARK_GREEN,
        "closed_color_1": CYAN,
        "closed_color_2": DARK_CYAN,
        "closed_color_3": TEAL,
        "path_color_1": GOLD,
        "path_color_2": PALE_YELLOW,
        "path_color_3": LIME_GREEN,
        "plane_color": WHITE,
        "bg_color": LIGHT_GREY,
        "grid_color": LIGHT_GREY,
    },
}
