from themes.colors import *

themes = {
    "Default": {
        "menu_bg_color": DARK_CREAM,
        "inactive_button_color": BTN_1,
        "active_button_color": ACT_BTN_1,
        "button_outline_color": ACT_BTN_1,
        "button_text_color": WHITE,
        "start_color": BTN_1,
        "end_color": BTN_2,
        "barrier_color": DARK_BROWN,
        "weight_color": LIGHT_BROWN,
        "look_color": LIGHT_BLUE,
        "open_color": LIGHT_BLUE,
        "open_color_1": BTN_1,
        "open_color_2": ACT_BTN_1,
        "closed_color": DARK_GREY,
        "closed_color_1": DARKER_GRAY,
        "closed_color_2": LIGHTER_GRAY,
        "closed_color_3": SOFT_BLUE,
        "path_color_1": BTN_1,
        "path_color_2": ACT_BTN_1,
        "path_color_3": BTN_2,
        "plane_color": WHITE,
        "bg_color": DARK_CREAM,
        "grid_color": DARKER_GRAY,
        "output_screen_color": SOFT_BLUE,
        "font_color": BLACK,
    },
    "Solarized": {
        "menu_bg_color":TEAL,
        "inactive_button_color":TEAL,
        "active_button_color":DARK_TEAL,
        "button_outline_color":TEAL_V2,
        "button_text_color":WHITE,
        "start_color": MAGENTA,
        "end_color": RED,
        "barrier_color": BLACK,
        "weight_color": BROWN,
        "look_color": BRIGHT_CYAN,
        "open_color": BRIGHT_GREEN,
        "open_color_1": BRIGHT_GREEN,
        "open_color_2": DARK_GREEN,
        "closed_color_1": CYAN,
        "closed_color_2": DARK_CYAN,
        "closed_color_3": TEAL,
        "path_color_1": GOLD,
        "path_color_2": PALE_YELLOW,
        "path_color_3": LIME_GREEN,
        "plane_color": WHITE,
        "bg_color": LIGHT_GREY,
        "grid_color": LIGHT_GREY,
    },
    "Dark": {
        "menu_bg_color":DARK_GREY,
        "inactive_button_color":DARK_GREY,
        "active_button_color":DARKER_GREY,
        "button_outline_color":DARK_GREY,
        "button_text_color":WHITE,
        "start_color": MAGENTA,
        "end_color": RED,
        "barrier_color": BLACK,
        "weight_color": BROWN,
        "look_color": BRIGHT_CYAN,
        "open_color": DARK_GREEN,
        "open_color_1": BRIGHT_GREEN,
        "open_color_2": DARK_GREEN,
        "closed_color_1": CYAN,
        "closed_color_2": DARK_CYAN,
        "closed_color_3": TEAL,
        "path_color_1": GOLD,
        "path_color_2": PALE_YELLOW,
        "path_color_3": LIME_GREEN,
        "plane_color": WHITE,
        "bg_color": DARK_GREY,
        "grid_color": DARK_GREY,
    },
    "Synthwave": {
        "menu_bg_color": DARK_PURPLE,
        "inactive_button_color": BRIGHT_MAGENTA,
        "active_button_color": BRIGHT_RED,
        "button_outline_color": BRIGHT_CYAN,
        "button_text_color": WHITE,
        "start_color": BRIGHT_MAGENTA,
        "end_color": BRIGHT_RED,
        "barrier_color": BRIGHT_GREEN,
        "weight_color": DARK_GREEN,
        "look_color": BRIGHT_CYAN,
        "open_color": BRIGHT_GREEN,
        "open_color_1": BRIGHT_GREEN,
        "open_color_2": DARK_GREEN,
        "closed_color_1": BRIGHT_CYAN,
        "closed_color_2": DARK_CYAN,
        "closed_color_3": TEAL,
        "path_color_1": GOLD,
        "path_color_2": PALE_YELLOW,
        "path_color_3": LIME_GREEN,
        "plane_color": WHITE,
        "bg_color": DARK_PURPLE,
        "grid_color": BRIGHT_MAGENTA,
    },
}
